### ISSUE TITLE
Filters on WFS?

### ISSUE THREAD

**Issue by tomchance** [azgs/azgs-leaflet#3]
Is it possible to apply filters other than dates on WFS layers? For example, 

filter=<PropertyIsEqualTo><PropertyName>natural</PropertyName><Literal>wetland</Literal></PropertyIsEqualTo>

I can see that the attributes can be used to style features, and that the date option code could be generalised to allow one to pass other filter options so that I could like to constrain the request to a subset of features to keep the data transfer fast.

I'd also like to filter by BBOX, I've looked at the code but it doesn't appear as though this is being done automatically by the area currently in view so a manual BBOX override would be useful.

Very sorry if this is a stupid question!

**Comment by rclark** [comment]
You're right -- I didn't build any attribute filtering because the projects that I was working on didn't require it. You're also right that the DateFilter code could be generalized to perform attribute filters, but note that the filtering will only work with a WFS server that can handle CQL queries encoded in a URL (i.e. Geoserver). 

BBOX filters could similarly be encoded as a CQL query using code similar to the DateFilter. But again, you're right that building a layer that dynamically updates depending on the map's current view presents different problems.

In retrospect, I didn't build so much a WFS layer as I built a Geoserver layer. I'm assuming a number of things that Geoserver gives you, but are not aspects required by the WFS specification. I'm hoping to get back to this project soon, refactor, and adjust things a bit. 

I think the Geoserver layer might find a better home in [Jason Sanford's excellent Vector Layers plugin](http://geojason.info/leaflet-vector-layers/).
